Config table
sourcecoursepoc/source-course-configuration pull request #27
Opened 2023-04-20 05:12 UTC by jayajoseph1

Exception Added

2023-04-24 12:23 UTC, shijukbabu-ust requested changes

2023-04-24 12:23 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/configuration/excpection/ResourceNotFoundException.java
> +package com.ust.sourcecourse.configuration.excpection;
Correct the package name. Take latest code from dev. There is already ResourceNotFoundException class added, but in exceptions package. You can use the same and delete this package.

2023-04-26 06:20 UTC, shijukbabu-ust requested changes

2023-04-26 06:20 UTC, shijukbabu-ust commented on src/main/resources/application.properties
Don't change this file yet.

2023-04-26 06:20 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/configuration/controller/SourcePocController.java
Delete this class

2023-04-26 06:41 UTC, jayajoseph1 commented on src/main/java/com/ust/sourcecourse/configuration/controller/SourcePocController.java
resolved

2023-04-26 07:06 UTC, jayajoseph1 commented on src/main/resources/application.properties
resolved

2023-04-26 07:58 UTC, shijukbabu-ust approved these changes

2023-04-26 07:58 UTC, merged